name: Enigma Images
favicon: null
layout_spectrum: 0.49555372330360115
typography_spectrum: 0.276056605624035
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.34049156308174133
  lightness: 0.7524131385143846
  saturation: 0.899096313631162
  rhythmicContrast: 0.3476410177536309
purpose: []
