name: Enigma Images
favicon: null
layout_spectrum: 0.01084
typography_spectrum: 0.65185
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#057139'
    - '#358b5f'
    - '#23ac6c'
    - '#00552b'
    - '#000000'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.899096313631162
  rhythmicContrast: 0.25
purpose: []
